# Generated by Django 4.2.1 on 2025-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('vram', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('pci', models.CharField(max_length=50)),
                ('vram_type', models.CharField(max_length=50)),
                ('memory_interface', models.PositiveIntegerField()),
                ('output_type', models.CharField(max_length=100)),
                ('gpu_clock', models.PositiveIntegerField()),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
