# Generated by Django 4.2.1 on 2025-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_interface',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='warranty',
            field=models.CharField(max_length=100),
        ),
    ]
