# Generated by Django 4.2.1 on 2025-05-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_gpu_gpu_clock_alter_gpu_memory_interface_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
