# Generated by Django 4.2.1 on 2025-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_id_gpu_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
