# Generated by Django 4.2.1 on 2025-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_gpu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('product_line', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=50)),
                ('cores', models.PositiveIntegerField()),
                ('potok', models.PositiveIntegerField()),
                ('cpu_clock', models.PositiveIntegerField()),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
