# Generated by Django 4.2.1 on 2025-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('type_size', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('psu_place', models.CharField(max_length=50)),
                ('body_material', models.CharField(max_length=50)),
                ('coolers_in', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('cooler_type', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=50)),
                ('tdp', models.PositiveIntegerField()),
                ('cooler_size', models.CharField(max_length=50)),
                ('connector_type', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('interface_pci', models.CharField(max_length=50)),
                ('digital_storage', models.PositiveIntegerField()),
                ('compatible_devices', models.CharField(max_length=200)),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=100)),
                ('memory_type', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('wattage', models.PositiveIntegerField()),
                ('formfactor', models.CharField(max_length=50)),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certificate', models.CharField(max_length=100)),
                ('warranty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=50)),
                ('memory_type', models.CharField(max_length=50)),
                ('memory', models.PositiveIntegerField()),
                ('one_module_memory', models.PositiveIntegerField()),
                ('moduls_in', models.PositiveIntegerField()),
                ('hertz', models.PositiveIntegerField()),
                ('timings', models.CharField(max_length=50)),
                ('xmp_support', models.BooleanField(default=False)),
            ],
        ),
    ]
