# Generated by Django 4.2.1 on 2025-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_case_cooler_memory_motherboard_powersupply_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
