# Generated by Django 4.2.1 on 2025-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cooler_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
