# Generated by Django 4.2.1 on 2025-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_memory_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(default='static/images/5970227.png', upload_to='store/images/'),
        ),
    ]
