# Generated by Django 4.2.1 on 2025-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_gpu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='image',
            field=models.ImageField(default='pc_store/static/store/images/5970227.png', upload_to='store/images/'),
        ),
    ]
