# Generated by Django 4.2.1 on 2025-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_gpu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='image',
            field=models.ImageField(upload_to='store/images/'),
        ),
    ]
