# Generated by Django 4.2.1 on 2025-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_gpu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='dlss',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='fg',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
