# Generated by Django 4.2.1 on 2025-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_gpu_dlss_gpu_fg'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
    ]
