# Generated by Django 4.2.1 on 2025-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_case_image_cooler_image_cpu_image_memory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='tdp',
            field=models.IntegerField(null=True),
        ),
    ]
