# Generated by Django 4.2.1 on 2025-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cpu_tdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupply',
            name='pins',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
