# Generated by Django 4.2.1 on 2025-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_powersupply_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupply',
            name='watt',
            field=models.IntegerField(null=True),
        ),
    ]
